

SELECT TEAM_ID,PLAYER_ID,
PLAYER_NAME,
POSITION,
HEIGHT FROM PLAYER p
WHERE HEIGHT=(SELECT MAX(HEIGHT) FROM PLAYER );

SELECT TEAM_ID ,TRUNC(AVG(HEIGHT)) 
	FROM PLAYER p
	GROUP BY TEAM_ID 
	ORDER BY TEAM_ID ;
	
SELECT *
 	FROM TEAM t ;