SELECT TEAM_NAME,AVG(HEIGHT) 
	FROM PLAYER p JOIN TEAM t
	USING(TEAM_ID)
	GROUP BY TEAM_NAME;
	
SELECT TEAM_NAME,ROUND(AVG(HEIGHT),1) 
	FROM PLAYER p JOIN TEAM t
	USING(TEAM_ID)
	GROUP BY TEAM_NAME
	ORDER BY AVG(HEIGHT) DESC;
CREATE TABLE PLAYER2 AS SELECT * FROM PLAYER;